### ISSUE TITLE
Cash Family subscription amount circle becomes not a circle on iPad Pro in portrait orientation

### ISSUE THREAD

**Issue by illintechnology** [cashmusic/platform#1013]
When viewing the family.cashmusic.org page  in iOS Safari in portrait on an iPad Pro the subscription amount circle is not a circle. See screenshot.

![img_1349](https://cloud.githubusercontent.com/assets/6120127/22578819/6663d93c-e980-11e6-8645-323751ad595e.PNG)

**Comment by christopherleckie** [comment]
Thanks for the heads-up! Will get it fixed up ASAP
