### ISSUE TITLE
Problem with "Delete Account"

### ISSUE THREAD

**Issue by TheodoreMichels** [cashmusic/platform#1064]
Hi all,
I'm wanting to just clear everything out and start from scratch, so I tried using the "Delete Account" function in "Account/Settings" but it's not working.

For what it's worth, after choosing "Yes do it" I see the following in the JavaScript console:
parsererror: SyntaxError: Unexpected end of JSON input

After that, the CASH icon just keeps spinning but the account doesn't actually seem to delete. I can continue to log in with my original info and it seems like everything is the same.

Thanks for your time,
Teddy

**Comment by paperscissors** [comment]
Hey Teddy, thanks for the heads up. Sounds like it's tanking on a 500 and sending back a garbage JSON response. I'll take a look and see what's doing.

Wondering, what's the impetus for starting from scratch? Wondering if there's a greater design/feature issue there we should be keeping in mind for future.

Best,
Tom

**Comment by TheodoreMichels** [comment]
Tom - I teach an intro web dev class for music industry students and we sometimes use CASH.
I usually just create a bunch of dummy content and throw everything away when I'm done - so not really a design or feature issue.

But I also noticed that test purchases didn't seem to be showing up in my activity feed (heard the same from a former student who uses the platform), so I just wanted to see if cleaning everything out would help. If you'd like, I can create another issue and give some more details on that - assuming somebody hasn't already.

Thanks for your time.

**Comment by paperscissors** [comment]
That's a great idea, the class.

When you say purchases not showing in activity feed, you mean on the main page when you first log into admin? It should show new purchases since the last time you logged in, I believe.

I'd go ahead and open a second ticket so I can keep track of these for you!

**Comment by TheodoreMichels** [comment]
Yeah, they're not showing on the Main Page when I log in.
Got it - I've opened another ticket.
Thanks again for your time Tom,
Teddy
