### ISSUE TITLE
Can't change credit card for CASH Family membership

### ISSUE THREAD

**Issue by ericsteuer** [cashmusic/platform#1085]
Hey hey, sorry for putting this in platform; seemed like the best place for Family stuff?

I need to change the credit card I use to pay for Family. After I log in to Family, I x out the overlay window with the content feed to find an "account" button (or similar), but don't see one. And because I've now x'd out the content feed, Family thinks I'm no longer logged in (I still see a Login option in the top menu).

Not crazy urgent, but the card I'm using is expiring soon and I'll need to input a new number.

**Comment by paperscissors** [comment]
you know @ericsteuer --- we are working on this but in the meantime i *think* i have it setup so if you try to sign up with the same email but different card it changes your subscription to the new card. i believe it set it up to do that as sort of an interim solution until i setup an "account" page. if not let me know and we can figure it out.
