### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by michaelizer** [cashmusic/platform#1197]
Hello, I would love to help you translate all those English files into Spanish. I just read about the project and can't wait to contribute. Please let me know if you want the help so I can start translating 
Thanks in advice for your answer and keep up the good work!

**Comment by paperscissors** [comment]
Thanks so much for dropping a line— we actually have the project about 90% translated into Spanish as of today, but we very much appreciate you reaching out!

Best,
Tom
