### ISSUE TITLE
Requesting for Filipino Translation

### ISSUE THREAD

**Issue by iam-strings** [cashmusic/platform#1198]

**Comment by caratzky** [comment]
May I do the filipino translation?

**Comment by paperscissors** [comment]
Hey @caratzky --- seeing the pull requests you pushed up. This is great. I'm going to make a `filipino-translation` branch off of master and change the pull requests to go to that. If you have any further changes if you could send the pull request to that branch instead, that would be great!

I have some more app.json changes coming soon, mostly for the subscriptions element.
