### ISSUE TITLE
Requesting for Cebuano translation

### ISSUE THREAD

**Issue by agentzero1** [cashmusic/platform#1257]
Good day sir im cebuano i want to translate your some code to cebuano

**Comment by paperscissors** [comment]
Hey @agentzero1, that would be great!

Instructions are here on the files that need translation: https://github.com/cashmusic/platform/wiki/CASH-Platform-Translations

Your best bet is to create a new branch and do a pull request when you're ready with the JSON and Markdown files!

Best,
Tom

**Comment by agentzero1** [comment]
Thank you sir
