### ISSUE TITLE
Brazilian Portuguese translation

### ISSUE THREAD

**Issue by Alender-steemit** [cashmusic/platform#1279]
Hello!

I want to help your project by making some translations to Brazilian Portuguese. I made a research and saw that you are making new branches for the translations. If it's of your interest to have some pt_br translations (help, documentation, interface and anything else that you need), please, make a new branch and I will start to help you!

**Comment by paperscissors** [comment]
Hey @Alender-steemit, yes please, that would be lovely! I've created a branch `brazilian-portuguese-translation`, and all the details are here: https://github.com/cashmusic/platform/wiki/CASH-Platform-Translations

Thanks much,
Tom

**Comment by Alender-steemit** [comment]
Thank you!
I will do my best give you awesome versions of pt_br files!
