### ISSUE TITLE
Request for Turkish translation

### ISSUE THREAD

**Issue by realkalinux** [cashmusic/platform#1297]
Hey, I want to translate this project into Turkish.
I'm very good at this, so I'll start with your permission.

**Comment by paperscissors** [comment]
Hey @realkalinux, this sounds great. I think someone started one but only contributed a few files. Have a look at the `turkish-translation` branch to see what's been contributed, and check out our translation wiki for what we're looking for: https://github.com/cashmusic/platform/wiki/CASH-Platform-Translations 

Thanks!
Tom
