### ISSUE TITLE
Translation: Lithuanian (LT)

### ISSUE THREAD

**Issue by jjimmyleo** [cashmusic/platform#1316]
I'm a native Lithuanian speaker and also more or less fluent in English. To provide a little bit of information about myself I'm an IT student living in London at the moment finishing my bachelors degree in a couple of months. I'm not extremely familiar with how translating works with this projects methods but by looking at it seems like it's all fairly simple to understand. If the developers are interested please do let me know I'll be able to start immediately. Thank you!

Edit: The tutorial page on how to translate shows everything that I need. I've pretty much started translating it now but still let me know if you are interested in it before i make a pull request to not clutter it all up for you guys. Thanks!

**Comment by paperscissors** [comment]
Hey @jjimmyleo, apologies for not answering on this issue--- thanks again for doing the translation, it's a huge help!
