### ISSUE TITLE
Album Art for Asset Release 

### ISSUE THREAD

**Issue by kevinclarkcomposer** [cashmusic/platform#268]
attaching images as cover art to a release isn't functioning. Clicking on the "Add that asset" button below:
![Screen Shot 2012-12-28 at 4 44 56 PM](https://f.cloud.github.com/assets/959884/34714/04c735dc-5138-11e2-9d5f-94a4d71cc77f.png)

Leads back to the asset detail page, but with this message added:
![Screen Shot 2012-12-28 at 4 45 10 PM](https://f.cloud.github.com/assets/959884/34716/2299bed6-5138-11e2-9796-3e0cb00d68e8.png)

And no other changes present. Clicking "add/edit cover" yields the same field as in the first image, but without any information entered. At no point does the uploaded image appear as the album cover. This is occurring in the hosted platform, in Chrome and Firefox, on OS X.8.2

**Comment by jessevondoom** [comment]
Closing though there are still issues. Documented in #271
