### ISSUE TITLE
Getting errors when trying to add a new 3rd party connection.

### ISSUE THREAD

**Issue by majimboo** [cashmusic/platform#344]
Nothing gets displayed when I click on the icons like paypal.

[Fri Apr 04 05:37:25 2014] [error] [client 10.0.2.2] PHP Notice:  Undefined variable: endpoint_parts in /vagrant/interfaces/php/admin/classes/AdminHelper.php on line 80, referer: http://localhost:8888/interfaces/php/admin/settings/connections/
[Fri Apr 04 05:37:27 2014] [error] [client 10.0.2.2] PHP Notice:  Undefined variable: endpoint_parts in /vagrant/interfaces/php/admin/classes/AdminHelper.php on line 80, referer: http://localhost:8888/interfaces/php/admin/settings/connections/add/com.paypal
[Fri Apr 04 05:37:28 2014] [error] [client 10.0.2.2] PHP Notice:  Undefined variable: endpoint_parts in /vagrant/interfaces/php/admin/classes/AdminHelper.php on line 80, referer: http://localhost:8888/interfaces/php/admin/settings/connections/add/com.mandrillapp
[Fri Apr 04 05:37:29 2014] [error] [client 10.0.2.2] PHP Notice:  Undefined variable: endpoint_parts in /vagrant/interfaces/php/admin/classes/AdminHelper.php on line 80, referer: http://localhost:8888/interfaces/php/admin/settings/connections/add/com.google.drive
[Fri Apr 04 05:37:31 2014] [error] [client 10.0.2.2] PHP Notice:  Undefined variable: endpoint_parts in /vagrant/interfaces/php/admin/classes/AdminHelper.php on line 80, referer: http://localhost:8888/interfaces/php/admin/settings/connections/add/com.google.drive
[Fri Apr 04 05:37:32 2014] [error] [client 10.0.2.2] PHP Notice:  Undefined variable: endpoint_parts in /vagrant/interfaces/php/admin/classes/AdminHelper.php on line 80, referer: http://localhost:8888/interfaces/php/admin/settings/
[Fri Apr 04 05:37:37 2014] [error] [client 10.0.2.2] PHP Notice:  Undefined variable: endpoint_parts in /vagrant/interfaces/php/admin/classes/AdminHelper.php on line 80, referer: http://localhost:8888/interfaces/php/admin/settings/connections/add/com.paypal
[Fri Apr 04 05:37:38 2014] [error] [client 10.0.2.2] PHP Notice:  Undefined variable: endpoint_parts in /vagrant/interfaces/php/admin/classes/AdminHelper.php on line 80, referer: http://localhost:8888/interfaces/php/admin/settings/
[Fri Apr 04 05:39:08 2014] [error] [client 10.0.2.2] PHP Notice:  Undefined variable: endpoint_parts in /vagrant/interfaces/php/admin/classes/AdminHelper.php on line 80, referer: http://localhost:8888/
[Fri Apr 04 05:39:29 2014] [error] [client 10.0.2.2] PHP Notice:  Undefined variable: endpoint_parts in /vagrant/interfaces/php/admin/classes/AdminHelper.php on line 80, referer: http://localhost:8888/

**Comment by jessevondoom** [comment]
Older version...fixed in new.
