### ISSUE TITLE
Firefox: Resized images change size on hover->opacity change

### ISSUE THREAD

**Issue by su** [cashmusic/platform#531]
In Firefox, the sponsor images at bottom of the homepage slightly rescale on hover. For some reason this sometimes takes a few attempts to trigger. Just keep shifting on/off them and you'll see it. This is apparently down to a [2yr-old bug](https://bugzilla.mozilla.org/show_bug.cgi?id=745549) but there's a workaround in there: add `box-shadow: #000 0em 0em 0em;` to the relevant rules, eg `.shuttleworth img` in front.css (I did a quick test in Firebug and it seems to work.)

This is obviously a pretty minor concern here, but might at some point happen somewhere more annoying, so filing for your reference.

**Comment by jessevondoom** [comment]
Site's been updated and doesn't appear to have this issue anymore.
