### ISSUE TITLE
Assets: main landing page

### ISSUE THREAD

**Issue by jessevondoom** [cashmusic/platform#561]
The current main page for assets will remain mostly intact, with several key enhancements. You can see some of them are style changes, but specifically:

  - Assets will show an icon if they have been monitized as a commerce item
  - More complete reworking of the file list

![assets_first_use_landing](https://cloud.githubusercontent.com/assets/368640/5326618/6d9b1bc4-7cd7-11e4-977a-995713ffb665.jpg)

**Comment by christopherleckie** [comment]
![screen shot 2015-01-19 at 12 35 19](https://cloud.githubusercontent.com/assets/5073839/5807383/b47c0346-9fd7-11e4-89f5-e01c1536041e.png)
In the asset edit pages i've moved the download code generator and define commerce settings into the asset preferences panel. This helps give the page a cleaner structure and hopefully makes editing an asset easier to understand for new users.

**Comment by jessevondoom** [comment]
These are all set save for some minor site-wide styling things...
