### ISSUE TITLE
Connection forms should show in main body

### ISSUE THREAD

**Issue by jessevondoom** [cashmusic/platform#563]
Currently the forms for adding a connection show in the sidebar along with connection types. At the very least the main forms should be shown in the main space rather than the sidebar, and we should explore moving the type selection OR current connection list back to the main page as well. If we find a more coherent presentation for that space we'll take a lot of stress out of the connection process.

**Comment by jessevondoom** [comment]
Opening in overlays. Looks good!

**Comment by christopherleckie** [comment]
There is a glitch here. Need to sort for clicking between connections in the list and a double click on existing connection.

**Comment by jessevondoom** [comment]
@christopherleckie ah okay. i'll reopen for now.

**Comment by jessevondoom** [comment]
All sorted.
