### ISSUE TITLE
People: main landing page 

### ISSUE THREAD

**Issue by jessevondoom** [cashmusic/platform#572]
A rework of the main landing page in the new style. Content is mostly the same — we're showing lists but also pushing Mandrill signups for mass mailings. (This may be hidden on launch of first use milestone, depending on progress of the mailing stuff.) If a user has already connected Mandrill (or if we're not exposing that stuff yet) the list will be full width. 

Screenshot:

![people_landing](https://cloud.githubusercontent.com/assets/368640/5419733/f1d842c4-8202-11e4-88e4-c4967378180f.jpg)

**Comment by ryanmyersdesign** [comment]
Not clear what increase/decrease in percentage is measuring (same feedback from the New Main Page). Below in the table I’m not sure what the up/down arrows are representing (increase/decrease of people on these lists? Engagement from each list?)

**Comment by jessevondoom** [comment]
Complete (and we removed the top up/down % stuff so it's just a straightforward list with growth numbers right inline.)
