### ISSUE TITLE
New element page

### ISSUE THREAD

**Issue by jessevondoom** [cashmusic/platform#576]
Clicking through to element details needs a better experience. This new page tackles multiple issues: 

  - Moving analytics up top while condensing the area they take up. Better quick view of things. 
  - Quick copy-to-clipboard for embed code
  - Embed preview area (hidden by default.)
  - Move settings to the universal settings style. They're not used much after setup so this gives a more direct look at what people need to see.

![element_landing_3](https://cloud.githubusercontent.com/assets/368640/5481804/9545d730-860b-11e4-86ae-4b83323b3787.jpg)

**Comment by ryanmyersdesign** [comment]
Code blocks, is there a common style for this? I think it’s inverted elsewhere (user page editing screen).

**Comment by christopherleckie** [comment]
Thanks for the input Ryan! There will be two styles one for in page editors like on elements pictured above and one for modal window editors like page editing screen. Hope that makes sense!
