### ISSUE TITLE
New main page

### ISSUE THREAD

**Issue by jessevondoom** [cashmusic/platform#577]
The current flow around the main page, campaigns, pages, and elements is...a mess. We didn't have time to get it really solid last round, so @christopherleckie has been working hard to refine the flow and communicate it visually. 

This new homepage focuses on a single campaign at a time (with a campaign selector) and visually groups the campaign together with the elements it contains. Element embed codes are available at a click and you can dive deeper just as easily. We're going for both easy access to stats and functionality, but also using the layout to communicate what a campaign is to people. 

The publish settings (in the new standard settings panel) gives equal priority to creating a page or embedding elements. This'll be open by default until a page has been created or an embed is registering visits (meaning it's been successfully embedded.) 

![dashboard_first_use_overlay_14_noelement](https://cloud.githubusercontent.com/assets/368640/5481908/1f39a2cc-860d-11e4-8f77-4f4a4de84378.jpg)

![dashboard_first_use_overlay_13](https://cloud.githubusercontent.com/assets/368640/5481910/240ca9c0-860d-11e4-9746-668df5365353.jpg)

**Comment by ryanmyersdesign** [comment]
It would be helpful to have a label next to the percentage in the campaign summary (next to total views) so as I user I can understand how this campaign is performing and being measured(decrease or increase from previous day/week/month).
Curious why there are two different button styles for the (+Add) buttons in the Associated Elements section. One seems to be the active button, and the other looks inactive.

**Comment by jessevondoom** [comment]
I still need to hook up (and explain) the percentage stuff, plus the page editor launch button

**Comment by jessevondoom** [comment]
Oh and image permanence for each campaign

**Comment by jessevondoom** [comment]
Only percentage bullshit now. Slow and glacial progress, FTW!

Up next: user testing!

**Comment by jessevondoom** [comment]
Okay we're actually hiding the performance stats until we can provide deeper context. Less is more right now, and more will be more later.
