### ISSUE TITLE
Download code redemption for multiple items produces overlap

### ISSUE THREAD

**Issue by tracysooming** [cashmusic/platform#589]
OBSERVED BEHAVIOUR:

A user created an asset with two files. He created a download code redemption campaign, which succeeds, but the redemption page produces overlapping links. 

His CASH page: http://records.sleepyvolcano.com/redeem/
Download code provided: krkmysdjhq (used twice, may not work again)
Screen cap:
![screen shot 2015-01-14 at 1 17 11 pm](https://cloud.githubusercontent.com/assets/3639313/5744606/3a9ec328-9bf0-11e4-8754-99f3ae48efe3.png)

I recreated the bug by creating an asset with two downloadable files and then publishing a download code redemption campaign. 
My CASH page: http://tracycash.cashmusic.org/
Download codes to test: srkmgmrm5z / 8rkmgekm5c
Screen cap:
![screen shot 2015-01-14 at 1 21 06 pm](https://cloud.githubusercontent.com/assets/3639313/5744605/3a9d31a2-9bf0-11e4-9c09-ec0e553ed34b.png)

EXPECTED BEHAVIOUR:

Upon redeeming a download code, a page should appear with non-overlapping links.

**Comment by christopherleckie** [comment]
Fixed 7 Pushed to master xo
