### ISSUE TITLE
Settings: Highlight confirm password box in red 

### ISSUE THREAD

**Issue by tracysooming** [cashmusic/platform#600]
The password field should light up red if, upon pressing the "Save changes" button, no password has been entered.

**Comment by jessevondoom** [comment]
I'm going to add a few details: 

THE PROBLEM
A user goes to the account settings page wanting to change their username or password. For that level of change we ask for their password again (just in case they left the window open, had a session hijacked somehow, etc.) At present we don't have it set as a requirement to complete the password field in the validation markup. 

THE SOLUTION
We should be requiring the password so the form won't be submitted without it. This will avoid confusion and give a contextual error to the user. We already have password validation, so it's just a matter of adding the correct class to the field.

cc: @christopherleckie

**Comment by christopherleckie** [comment]
Added in new user enhancements sprint on Improve-First/New-User-Experience branch
