### ISSUE TITLE
Clicking between connection settings is awkward

### ISSUE THREAD

**Issue by waferbaby** [cashmusic/platform#610]
When I've clicked a connection setting item for one service (Amazon), and then click on another service, I would expect its panel to pop up. Instead, it just dismisses the current one. See attached, in order (1-3).

![1](https://cloud.githubusercontent.com/assets/1027/6422591/6d33704c-be8f-11e4-98cd-a19e4443a8bf.png)
![2](https://cloud.githubusercontent.com/assets/1027/6422589/67985d5a-be8f-11e4-92df-dc161f7ff7b7.png)
![3](https://cloud.githubusercontent.com/assets/1027/6422590/67b1a882-be8f-11e4-8b78-02b96e9bfa16.png)

**Comment by waferbaby** [comment]
Somewhat relatedly, if you're in say, Amazon's settings and enter incorrect data, you get the error message (good), but then that message will stay up forever (less good), even when switching in and out of other services. Also, the browser's URL has now become the finalize OAuth URL, and stays on that.

![4](https://cloud.githubusercontent.com/assets/1027/6422713/8465c304-be90-11e4-87ad-1a7e01aa016d.png)

**Comment by jessevondoom** [comment]
Ah yeah. These predate the nicer error redirects. I'll hook up a nicer overlay error then redirect. Good catch. The click-between thing is something Chris saw too. I'm going to poke around in that JS and look at making it not suck.

**Comment by maggiev23** [comment]
I was just about to say something about this. nice catch daniel!

**Comment by jessevondoom** [comment]
Fixed the selection stuff locally, working on a fix for the messaging now. Will push both soon.
