### ISSUE TITLE
After installing and Forking site has errors and looks nothing like http://cashmusic.org/

### ISSUE THREAD

**Issue by MoseyM** [cashmusic/platform#611]
I already had Virtual Box installed and these are the steps in order:

1. Forked repository
2. Created new vagrant directory and made connection to directory.
3. cloned repository into directory
4. vagrant ssh and entered command "make install"
-Was done within the platform directory 
5. Accessed site and received errors of files missing. "docs/assets.." shows it should be "interfaces/docs/assets"

I can provide screenshots. Could this be an error for users who already has Virtual Box installed?

**Comment by jessevondoom** [comment]
Hi! 

Actually the `make` stuff is all leftover from earlier, and the last of it is finally going away when we merge in a bigger release branch soon. All you need is the `vagrant up` and the platform should be running and happy for testing with a dev@cashmusic.org user (password: "dev")

There are quickie instructions in the main README, or a more detailed look here: 

https://cashmusic.org/docs/

...probably worth trashing your local clone and starting over though...the old `make install` process edited a few files.

**Comment by MoseyM** [comment]
Will do. Thank you for the quick response!

**Comment by jessevondoom** [comment]
Of course! Let me know if you run into any trouble. Next week's changes are going to be pretty big, but after that we should be back on a more continuous flow with updates.
