### ISSUE TITLE
Campaign editor flow loses context

### ISSUE THREAD

**Issue by waferbaby** [cashmusic/platform#612]
This is the flow from the main page, after I hover over my campaign and choose 'Edit' - I end up in a weird context-less place suddenly.

![1](https://cloud.githubusercontent.com/assets/1027/6472345/8bc82506-c1a6-11e4-96d4-363dd730faea.png)
![2](https://cloud.githubusercontent.com/assets/1027/6472346/8db32d5c-c1a6-11e4-8254-305296080327.png)
![3](https://cloud.githubusercontent.com/assets/1027/6472347/8f53c270-c1a6-11e4-84ac-97f08b89c6e7.png)
![4](https://cloud.githubusercontent.com/assets/1027/6472350/9196f93a-c1a6-11e4-9061-5949880a0e31.png)

**Comment by waferbaby** [comment]
I guess I would expect to be back where I started initially in the first image.

**Comment by christopherleckie** [comment]
Yeah, need to update that throughout. The norm is to get kicked back to edit when you should end up back where you started.

**Comment by jessevondoom** [comment]
#butts
