### ISSUE TITLE
It's possible to 'create' an empty Event

### ISSUE THREAD

**Issue by waferbaby** [cashmusic/platform#613]
You can choose to create an event, and it looks as though it goes through, but there's no actual event created in the end.

![1](https://cloud.githubusercontent.com/assets/1027/6473272/32354b0c-c1ad-11e4-9b2c-e0e05a2efbcb.png)
![2](https://cloud.githubusercontent.com/assets/1027/6473271/32328b56-c1ad-11e4-8c4e-5fed4087533b.png)
![3](https://cloud.githubusercontent.com/assets/1027/6473270/32300584-c1ad-11e4-82a2-2c92f0921919.png)

**Comment by christopherleckie** [comment]
Added Required fields to the form
