### ISSUE TITLE
Last remaining campaign will not show when all other campaigns have been deleted

### ISSUE THREAD

**Issue by tracysooming** [cashmusic/platform#614]
OBSERVED BEHAVIOUR:

If a user with multiple campaigns deletes all their campaigns, the last remaining one will not load on their main page. This problem can only be worked around by logging out and then logging back in.

![screen shot 2015-03-06 at 3 16 04 pm](https://cloud.githubusercontent.com/assets/3639313/6535605/1a98997c-c414-11e4-9a51-daf902ecc758.png)

DESIRED BEHAVIOUR:

Upon deleting the second-to-last campaign, after yielding the "Success. Deleted." screen, the platform should take the user back to a main page featuring the remaining campaign.

![screen shot 2015-03-06 at 3 19 38 pm](https://cloud.githubusercontent.com/assets/3639313/6535620/414d7b14-c414-11e4-9121-d42f496527ed.png)

**Comment by jessevondoom** [comment]
All changed in the new flow. Addressed and fixed
