### ISSUE TITLE
S3 uploads do not show up in bucket

### ISSUE THREAD

**Issue by tracysooming** [cashmusic/platform#644]
OBSERVED BEHAVIOUR:

Files uploaded to Assets via an S3 account do not show up in the bucket. In Chrome, user is taken to a success page and then brought back to the release page. In Firefox, the C x M loading graphic flashes in perpetuity. In Safari, an invalid certificate prompt arises, finally yielding an Access Denied page.

The platform does successfully create a cashmusic bucket, but always remains empty, despite the success message.

Bug first reported by a user and then replicated by three CASH staff. Please see screencaps below.

Firefox:
![screen shot 2015-03-24 at 6 59 10 pm](https://cloud.githubusercontent.com/assets/3639313/6815137/52829cd8-d25c-11e4-9840-01044d49c81c.png)

Chrome:
![screen shot 2015-03-24 at 7 30 39 pm](https://cloud.githubusercontent.com/assets/3639313/6815133/4e7712a4-d25c-11e4-9649-6c704eb60d88.png)

Safari:
![image](https://cloud.githubusercontent.com/assets/3639313/6815120/30bece78-d25c-11e4-821f-8a3f2efb21a9.png)

DESIRED BEHAVIOUR:

A file uploaded should yield a success message, and the corresponding file should appear in the CASH-created S3 bucket.

**Comment by tracysooming** [comment]
@waferbaby just sent this Invalid Certification screencap my way (Safari)

![image](https://cloud.githubusercontent.com/assets/3639313/6815178/c05b14ec-d25c-11e4-9bb4-220df62a1265.png)

**Comment by jessevondoom** [comment]
FIXED! It was the cert — dots are perfectly valid S3 bucket names but they don't resolve under the amazon *. cert. Changing convention to dashes fixed it.

**Comment by waferbaby** [comment]
:+1: Nice find!
