### ISSUE TITLE
Elements do not have sufficient padding/margin

### ISSUE THREAD

**Issue by tracysooming** [cashmusic/platform#646]
OBSERVED BEHAVIOUR:

When two or more elements are added to a campaign using the easy click-and-add tool, they are not adequately spaced and push up against each other. Paragraph or break tags must be used to space them out properly.

![screen shot 2015-03-25 at 9 07 04 pm](https://cloud.githubusercontent.com/assets/3639313/6838655/75be8004-d333-11e4-82b1-bc62778024ee.png)

DESIRED BEHAVIOUR:

Elements should be sufficiently spaced out to be both visually pleasing as well as logically disparate.

**Comment by jessevondoom** [comment]
Hey @christopherleckie — this is all addressed in the last layout changes, right? We can probably close this one.

**Comment by christopherleckie** [comment]
@jessevondoom yep!
