### ISSUE TITLE
Embedded email elements adding scrollbar

### ISSUE THREAD

**Issue by tmray** [cashmusic/platform#663]
I've embedded an email for download element on my site. For a week or so it looked fine.
But this weekend the submit button now shows underneath the email input field and this causes the whole thing to add a scroll bar to the iframe so things are getting cut off.

**Comment by tmray** [comment]
**Update:** I realized I still had the old `js.cashmusic.org/cashmusic.js` cdn in the header. 

Changed that to the new `cashmusic.org/public/cashmusic.js` and that solved the scroll bar issue. 

But the submit button still gets pushed underneath the email input field. So that's still an existing issue for me. Not a deal breaker but design-wise it just bugs me :)

**Comment by jessevondoom** [comment]
Will look into our responsive styles. It's not supposed to push the button down unless things are really tight. Thanks!
