### ISSUE TITLE
JSON Parse Error

### ISSUE THREAD

**Issue by jeffro-** [cashmusic/platform#730]
I keep getting this error message with an embedded email form. 

<img width="801" alt="screen shot 2015-09-05 at 10 01 38 pm" src="https://cloud.githubusercontent.com/assets/8499163/9702586/b4fbf80c-5419-11e5-9d64-7df8052022df.png">

It also stops my page from rendering.
http://jeffromusic.com

Anyone know what's going on?

**Comment by jessevondoom** [comment]
So I've seen the error before but it's never been a blocking thing. It was so inconsistent that I haven't taken a real run at debugging. Here's a few things:

  - Took a look at your website. It's commented out right now, so I downloaded all the files and un-commented the element in hopes of seeing the error. No luck. It embedded fine for me. 
  - Poked around the code and think I've found the spot that might be causing the error, but still can't trip it intentionally — do you have a copy of your site that causes the error consistently?
  - Are you sure it was this error that was stopping the page from rendering? (Are things how you expected now that it's commented out?
  - What browser? Looks like Chrome's debugging panel, yeah? 

I'll try to get this thing breaking consistently if I can so I can get a real fix sorted. Let me know whatever else you can though. It'd be a huge help!

j

**Comment by jeffro-** [comment]
I found out what it was in the forum. You guys changed the embed code to where you had to add an extra thing to what it was. Not sure what it was right now.

**Comment by jessevondoom** [comment]
Adding some basic research in here in case it pops up again. http://stackoverflow.com/questions/19625960/syntaxerror-json-parse-error-unexpected-identifier-object
