### ISSUE TITLE
Adding Elements don't work

### ISSUE THREAD

**Issue by punchi** [cashmusic/platform#732]
After an aparently successfully installation with cashmusic_web_installer.php, after login in and going to "Elements: Add Elements", the list of elements are shown without any image

![elements](https://cloud.githubusercontent.com/assets/142407/10030391/dee1a342-614d-11e5-84a5-73e6b225946d.png)

After this, when selecting one element, (like clicking on /admin/elements/add/digitalpurchase), every element goes to gray, and nothing happens

![elements2](https://cloud.githubusercontent.com/assets/142407/10030509/5af23708-614e-11e5-83da-440d8992d425.png)

It looks like this is critical, as you can't continue using the software, but I couldn't label this issue as it.

Thanks!

**Comment by jessevondoom** [comment]
This is a (very) old version of the software from an equally old version of the installer. I'll take a look through the docs to find where the link came from...
