### ISSUE TITLE
Main page Redesign

### ISSUE THREAD

**Issue by christopherleckie** [cashmusic/platform#751]
Our plan is to break out the main page into three tabbed areas Activity, Embeds & Your Page. To make the platform easier to use and understand conceptually, especially for new users. Initial designs below...

![dashboard_activity_full_compressed_4_2016_1024](https://cloud.githubusercontent.com/assets/5073839/13016838/06b938c4-d176-11e5-8610-54b71c923548.jpg)

![dashboard_embeds_full_comp_1_w_baseline_2016_1024](https://cloud.githubusercontent.com/assets/5073839/13016954/a7b9ea84-d176-11e5-948d-5cfe6667ebd9.jpg)

![dashboard_page_full_comp_1_w_baseline_2016_1024](https://cloud.githubusercontent.com/assets/5073839/13016980/cdecf6b0-d176-11e5-8970-b372ee86dc2c.jpg)

**Comment by paperscissors** [comment]
This is a lot easier to follow, I think it's great! It's a lot more clear what you can do when you go to each tab, and the accessibility of the information is a huge bonus.

+6 dexterity.

Raising the bar for everyone in the game.

**Comment by jessevondoom** [comment]
nailed it.
