### ISSUE TITLE
Zero dollar + pay-at-least pricing + suggested price

### ISSUE THREAD

**Issue by zirafa** [cashmusic/platform#754]
Apologies if this is a duplicate issue (searched but didn't find one) but is it possible to create an inventory item for sale that is a zero dollar minimum with pay-at-least pricing? For example, the widget would say $5.00 but that could be edited up higher or down lower to $0.00 for a free purchase. I guess the trick here might be something like if the user enters in $0.00 you'd actually want to switch the behavior of the widget to be email-for-download instead of redirect them to paypal.

**Comment by jessevondoom** [comment]
Currently you can enter $0.00 and it will work. We don't switch to an email collection, we simply allow the download to go through as a giveaway. We have discussed moving to email collection instead, but I'm not sure if that'd be the route we go or not. (Gets conplex in a cart situation, etc.)

**Comment by zirafa** [comment]
Thanks. Odd, when I tried entering $0.00 the widget would hang saying "redirecting". It might have been a weird thing with my localhost setup though, not sure.

**Comment by jessevondoom** [comment]
Ah weird. Sounds almost like a mistake in the asset setup...is the redirect working if you put in a positive dollar amount for testing or do an email capture? We're about 90% of the way through a full rework of all that code, so I want to make sure we don't pull any bugs forward with us...

**Comment by zirafa** [comment]
Yes, the redirect seemed to work with a positive dollar amount or email capture.

**Comment by waynedpj** [comment]
actually i am seeing the same never ending redirection on $0 amounts with a secure download element embedded in a very [simple HTML test page](http://waynedpj.in-giro.org/temporaneo/CASH/).  note however that the element works fine with $0 amounts on the cashmusic.org hosted [single campaign page](http://waynedpj.cashmusic.org/), though i assume that is not being embedded in the same way (i.e. via cashmusic.js).  i originally had posted to the support forums if you need [more details and a screenshot](http://help.cashmusic.org/discussions/problems/22852-secure-download-element-html-embed-no-working), or let me know, i would be glad to help debug this.

thanks.

**Comment by waynedpj** [comment]
seems to be fixed with latest updates, thanks!
