### ISSUE TITLE
Translation: ICELANDIC

### ISSUE THREAD

**Issue by johannesgunnar** [cashmusic/platform#898]
![skjamynd fra 2016-07-06 21-14-52](https://cloud.githubusercontent.com/assets/2924543/16634770/bb7bc91a-43be-11e6-8206-e2fab745534b.png)
I've started working on an Icelandic translation for the CASH Music platform.

Icelandic is my first language, English is my second. I am familiar with json and am an amateur programmer.  I have also contributed translations to various open source projects like for example Ubuntu, and Movim.

I am hoping to be able to contribute Icelandic translation to the whole platform.

If there are any other icelandic speakers out there, it would be lovely to have them join in on the fun as having an extra pair of eyes to at the very least review my translations would help a lot.

**Comment by jessevondoom** [comment]
This is SO FUCKING RAD!

I'll try to see if we can find a few other people. LOVE!

**Comment by christopherleckie** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by johannesgunnar** [comment]
<3

Do note that I don't have much experience with collaborating with people over git. Most of my git knowledge is restricted to private projects, so I might need some hand holding in the future regarding branches, pull requests and such.

But for now, I just cloned the repo to my computer and am adding the icelandic translations whenever I have free time. I assume I don't need to worry about branches until I start committing and such?

**Comment by paperscissors** [comment]
@johannesgunnar  you might as well start off the bat with a clean branch--- that way you can push it to the repo and not have to worry about losing work.

What I'd do is create a branch off of what you're doing on master now--- then switch back to master and revert any changes you made there.

A little confusing to start but it'll probably save some turbulence for you down the road. 

Great to have the help!

**Comment by johannesgunnar** [comment]
So, I finally finished my first version of the icelandic translation, but obviously it's been quite a lot of time since the initial fork. Is there anything I need to keep in mind before submitting a pull request? Can I somehow pull in all the changes from the main repo to my fork done in the platform to make sure the translations are still valid to this day? 

[https://github.com/johannesgunnar/platform/tree/translation-icelandic](translation-icelandic branch)

**Comment by christopherleckie** [comment]
Oh my word! @johannesgunnar This is beyond awesome!! You are the best! I think you'd best sync with the master branch first. I don't think you'll see any conflicts (let us know if you need any help with that if you come across any) From there you should be able to submit a PR! So excited! 🎉
